# Generated by Django 3.0.7 on 2020-07-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpeta',
            old_name='title',
            new_name='caratula',
        ),
        migrations.RenameField(
            model_name='carpeta',
            old_name='author',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='carpeta',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='carpeta',
            old_name='created_date',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='carpeta',
            old_name='published_date',
            new_name='fecha_publicacion',
        ),
    ]
