# Generated by Django 3.0.7 on 2020-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_auto_20200702_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='año',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='nro_expediente',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
