# Generated by Django 3.0.7 on 2020-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20200702_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='Providencia_de_autos_firme',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='secretaria',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
